version: '2'

services:
  edge-impulse:
    build: ./ei
    privileged: true
    ports:
      - "1337:1337"
  cam:
    build: ./cam
    privileged: true
    volumes:
      - "bdi_storage:/app/storage" # Storage for the File Manager. See docs for more info.
  
  webserver:
    build: ./webserver
    ports:
      - "5000:80"
    volumes:
      -  'bdi_storage:/app/storage'
  
  node-red:
    image: bh.cr/balenalabs/balena-node-red-aarch64
    container_name: node-red
    privileged: true
    restart: unless-stopped
    volumes:
        - 'node-red-data:/data'
    labels:
        io.balena.features.dbus: '1'
        io.balena.features.sysfs: '1'
        io.balena.features.supervisor-api: '1'
        io.balena.features.balena-api: '1'
    ports:
        - 80:80
    environment:
        PORT: 80
        USERNAME: "balena"
        PASSWORD: "balena"
        ENCRIPTION_KEY: "balena"
    cap_add:
        - SYS_RAWIO
    devices:
        - "/dev/mem:/dev/mem"
        - "/dev/gpiomem:/dev/gpiomem"
        - "/dev/i2c-1:/dev/i2c-1"

  mqtt:
    image: eclipse-mosquitto:1.6.15
    container_name: mqtt
    ports:
      - "1883:1883"
    restart: always

  influxdb:
    image: influxdb:1.7.11
    container_name: influxdb
    restart: unless-stopped
    volumes:
        - influxdb-data:/var/lib/influxdb
        - influxdb-etc:/etc/influxdb

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
        - "8080:3000"
    volumes:
        - "grafana-data:/data"
      
volumes:
  bdi_storage:
  node-red-data:
  influxdb-data:
  influxdb-etc:
  grafana-data:

